import { useState, useRef, useEffect, useCallback } from 'react'
import 'leaflet/dist/leaflet.css'
import './styles/theme.css'
import { ICON_MAP, SEVERITY, FLOW_NODES, FLOW_CONNECTIONS, BASE_LAYERS, COPERNICUS_INSTANCE, SUDAN_EVENT, createEvent, computeStats, buildSystemPrompt, renderEventToMap, BRIEF_ANALYSIS_PROMPT, eventToGeoJSON, eventToCSV, eventToReport, encodeShare, decodeShare, INC_TYPES, SEV_LEVELS, buildOverpassQuery } from './data/events.js'
import { t, LANGS } from './data/i18n.js'

const ls=(k,fb)=>{try{const v=localStorage.getItem('cp_'+k);return v!==null?JSON.parse(v):fb}catch{return fb}}
const ss=(k,v)=>{try{localStorage.setItem('cp_'+k,JSON.stringify(v))}catch{}}
const dlFile=(c,f,m='text/plain')=>{const b=new Blob([c],{type:m});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=f;a.click();URL.revokeObjectURL(u)}
function makeTile(Lf,id,th){const T={osm:()=>Lf.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OSM",maxZoom:19}),dark:()=>Lf.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"© CartoDB",maxZoom:20}),hot:()=>Lf.tileLayer("https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",{attribution:"© OSM, HOT",maxZoom:19}),esri:()=>Lf.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"© Esri",maxZoom:19}),topo:()=>Lf.tileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",{attribution:"© OpenTopoMap",maxZoom:17})};if(id==='osm'&&th==='dark')return T.dark();return(T[id]||T.osm)()}

// Shared View
function SharedView({event}){
  const mR=useRef(null),cR=useRef(null),stats=computeStats(event),sI=[...(event.incidents||[])].sort((a,b)=>a.dt.localeCompare(b.dt))
  useEffect(()=>{document.documentElement.setAttribute('data-theme','dark')},[])
  useEffect(()=>{if(mR.current)return;import('leaflet').then(mod=>{const L=mod.default||mod;delete L.Icon.Default.prototype._getIconUrl;L.Icon.Default.mergeOptions({iconRetinaUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png'});const m=L.map(cR.current,{zoomControl:true}).setView(event.region?.center||[9.5,30.5],6);mR.current=m;L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:20}).addTo(m);const layers=renderEventToMap(L,event,true);Object.values(layers).forEach(l=>l.addTo(m));if(event.region?.bounds)m.fitBounds(event.region.bounds,{padding:[30,30]})})},[])
  return(<div style={{width:'100vw',height:'100vh',display:'flex',flexDirection:'column',background:'var(--bg-primary)'}}>
    <div style={{display:'flex',alignItems:'center',gap:10,padding:'10px 16px',borderBottom:'1px solid var(--border-primary)',background:'var(--bg-secondary)',flexShrink:0}}><span style={{width:8,height:8,borderRadius:'50%',background:'var(--danger)'}}/><span style={{fontSize:'calc(var(--fs)*.82)',fontWeight:700}}>CORRIDOR PLANNER</span><span style={{fontSize:'calc(var(--fs)*.5)',padding:'2px 6px',borderRadius:3,background:'var(--accent-bg)',color:'var(--accent)',fontWeight:700}}>SHARED</span><span style={{marginLeft:'auto',fontSize:'calc(var(--fs)*.55)',padding:'2px 8px',borderRadius:3,background:(SEVERITY[event.severity]||SEVERITY.medium).bg,color:(SEVERITY[event.severity]||SEVERITY.medium).color,fontWeight:700}}>{event.severity?.toUpperCase()}</span></div>
    <div style={{flex:1,display:'flex',overflow:'hidden'}}>
      <div style={{width:340,minWidth:340,display:'flex',flexDirection:'column',background:'var(--bg-secondary)',borderRight:'1px solid var(--border-primary)',overflowY:'auto'}}>
        <div style={{padding:'14px 16px',borderBottom:'1px solid var(--border-subtle)'}}><div style={{fontSize:'calc(var(--fs)*.92)',fontWeight:700,marginBottom:6}}>{event.name}</div><div style={{fontSize:'calc(var(--fs)*.72)',color:'var(--text-secondary)',lineHeight:1.7}}>{event.brief}</div></div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:3,padding:'8px 12px',borderBottom:'1px solid var(--border-subtle)'}}>{stats.map(s=>(<div key={s.label} style={{padding:'5px 2px',borderRadius:4,textAlign:'center',background:'var(--surface-card)'}}><div style={{fontSize:'calc(var(--fs)*1)',fontWeight:700,color:s.color}}>{s.value}</div><div style={{fontSize:'calc(var(--fs)*.45)',color:'var(--text-muted)'}}>{s.label}</div></div>))}</div>
        <div style={{padding:'10px 16px',flex:1}}><div style={{fontSize:'calc(var(--fs)*.6)',fontWeight:700,color:'var(--text-muted)',marginBottom:6,textTransform:'uppercase'}}>Incidents ({sI.length})</div>{sI.map(inc=>{const sv=SEVERITY[inc.s]||SEVERITY.medium;return(<div key={inc.id} onClick={()=>mR.current?.setView([inc.a,inc.o],9)} style={{padding:'6px 8px',borderRadius:6,marginBottom:3,cursor:'pointer',border:'1px solid var(--border-primary)',background:'var(--surface-card)',fontSize:'calc(var(--fs)*.68)'}}><div style={{display:'flex',alignItems:'center',gap:5}}><span>{ICON_MAP[inc.tp]||'⚠️'}</span><span style={{flex:1,fontWeight:600}}>{inc.ti}</span><span style={{fontSize:'calc(var(--fs)*.5)',padding:'1px 5px',borderRadius:3,fontWeight:700,background:sv.bg,color:sv.color}}>{inc.s.toUpperCase()}</span></div><div style={{fontSize:'calc(var(--fs)*.55)',color:'var(--text-faint)',marginTop:2}}>{inc.dt}</div></div>)})}</div>
      </div>
      <div style={{flex:1,position:'relative'}}><div ref={cR} style={{width:'100%',height:'100%'}}/>{sI.length>0&&(<div style={{position:'absolute',bottom:16,left:'50%',transform:'translateX(-50%)',zIndex:1000,display:'flex',gap:8,background:'var(--glass-strong)',border:'1px solid var(--border-primary)',borderRadius:12,padding:'10px 18px',alignItems:'center'}}><span style={{fontSize:'calc(var(--fs)*.72)',color:'var(--text-muted)',fontWeight:700,marginRight:6}}>TIMELINE</span>{sI.map(inc=><div key={inc.id} onClick={()=>mR.current?.setView([inc.a,inc.o],9)} style={{display:'flex',flexDirection:'column',alignItems:'center',cursor:'pointer',padding:'4px 8px',borderRadius:8}}><span style={{fontSize:'calc(var(--fs)*1.3)'}}>{ICON_MAP[inc.tp]||'⚠️'}</span><span style={{fontSize:'calc(var(--fs)*.62)',color:(SEVERITY[inc.s]||SEVERITY.medium).color,marginTop:3,fontWeight:700}}>{inc.dt.slice(5)}</span></div>)}</div>)}</div>
    </div></div>)
}

// ══════════════════════════════════════════════════
export default function App(){
  const[sharedEvent,setSharedEvent]=useState(null)
  useEffect(()=>{const h=window.location.hash;if(h.startsWith('#/share/')){const ev=decodeShare(h.slice(8));if(ev)setSharedEvent(ev)}},[])
  if(sharedEvent)return<SharedView event={sharedEvent}/>

  const[theme,setTheme]=useState(()=>ls('theme','light'))
  const[lang,setLang]=useState(()=>ls('lang','en'))
  const[view,setView]=useState('map')
  const[panelOpen,setPanelOpen]=useState(()=>ls('panelOpen',true))
  const[fs,setFs]=useState(()=>ls('fs',13))
  const[showSettings,setShowSettings]=useState(false)
  const[settingsTab,setSettingsTab]=useState('appearance')
  const[baseLayerId,setBaseLayerId]=useState(()=>ls('bl','osm'))
  const[sentinel2,setSentinel2]=useState(false)
  const[dataLayers,setDataLayers]=useState({incidents:true,access:true,risks:true,corridor:true})
  const[apiKey,setApiKey]=useState(()=>ls('apiKey',''))
  const[aiModel,setAiModel]=useState(()=>ls('aiModel','claude-sonnet-4-20250514'))
  const[aiStatus,setAiStatus]=useState('unconfigured')
  const[mapAnims,setMapAnims]=useState(()=>ls('mapAnims',true))
  const[events,setEvents]=useState(()=>ls('events',[SUDAN_EVENT]))
  const[activeEventId,setActiveEventId]=useState(()=>ls('activeEvent',SUDAN_EVENT.id))
  const[detailOpen,setDetailOpen]=useState(false)
  const[detailTab,setDetailTab]=useState('overview')
  const[searchQuery,setSearchQuery]=useState('')
  const[chatMsgs,setChatMsgs]=useState({})
  const[chatHist,setChatHist]=useState({})
  const[inputVal,setInputVal]=useState('')
  const[busy,setBusy]=useState(false)
  const[noteInput,setNoteInput]=useState('')
  const[briefInput,setBriefInput]=useState('')
  const[briefAnalyzing,setBriefAnalyzing]=useState(false)
  const[showArchived,setShowArchived]=useState(false)
  const[showShareModal,setShowShareModal]=useState(false)
  const[shareUrl,setShareUrl]=useState('')
  const[showExportMenu,setShowExportMenu]=useState(false)
  const[copyFeedback,setCopyFeedback]=useState('')
  const[showIncForm,setShowIncForm]=useState(false)
  const[incForm,setIncForm]=useState({ti:'',d:'',tp:'displacement',s:'medium',ac:'',og:'',a:null,o:null})
  const[mapClickMode,setMapClickMode]=useState(false)
  const[infraLayers,setInfraLayers]=useState({})
  const[infraLoading,setInfraLoading]=useState('')

  const mapContainerRef=useRef(null),mapRef=useRef(null),LfRef=useRef(null),baseLayerRef=useRef(null)
  const sentinelRef=useRef(null),eventLayersRef=useRef({}),chatEndRef=useRef(null),settingsRef=useRef(null)
  const infraGroupsRef=useRef({}),clickMarkerRef=useRef(null)

  const _=key=>t(key,lang)
  const dir=LANGS.find(l=>l.id===lang)?.dir||'ltr'
  const ae=events.find(e=>e.id===activeEventId)||events[0]
  const stats=computeStats(ae)
  const fEvts=events.filter(e=>e.name.toLowerCase().includes(searchQuery.toLowerCase())||(e.brief||'').toLowerCase().includes(searchQuery.toLowerCase()))
  const cMsgs=chatMsgs[activeEventId]||[{role:'a',text:`Event "${ae?.name}" loaded.`}]
  const sInc=[...(ae?.incidents||[])].sort((a,b)=>a.dt.localeCompare(b.dt))
  const aBriefs=(ae?.briefs||[]).filter(b=>!b.archived)
  const xBriefs=(ae?.briefs||[]).filter(b=>b.archived)
  const inp={padding:'7px 8px',borderRadius:6,fontSize:'calc(var(--fs)*.72)',background:'var(--surface-input)',border:'1px solid var(--border-input)',color:'var(--text-primary)',fontFamily:'inherit',outline:'none',width:'100%'}
  const svB=s=>({fontSize:'calc(var(--fs)*.55)',padding:'1px 6px',borderRadius:3,fontWeight:700,background:(SEVERITY[s]||SEVERITY.medium).bg,color:(SEVERITY[s]||SEVERITY.medium).color,whiteSpace:'nowrap'})

  useEffect(()=>{document.documentElement.setAttribute('data-theme',theme);document.documentElement.setAttribute('dir',dir);ss('theme',theme)},[theme,dir])
  useEffect(()=>{document.documentElement.style.setProperty('--fs',fs+'px');ss('fs',fs)},[fs])
  useEffect(()=>{ss('panelOpen',panelOpen)},[panelOpen])
  useEffect(()=>{setAiStatus(apiKey?'ready':'unconfigured');ss('apiKey',apiKey)},[apiKey])
  useEffect(()=>{ss('aiModel',aiModel)},[aiModel])
  useEffect(()=>{ss('events',events)},[events])
  useEffect(()=>{ss('activeEvent',activeEventId)},[activeEventId])
  useEffect(()=>{ss('mapAnims',mapAnims)},[mapAnims])
  useEffect(()=>{ss('lang',lang)},[lang])
  useEffect(()=>{chatEndRef.current?.scrollIntoView({behavior:'smooth'})},[cMsgs])
  useEffect(()=>{const h=e=>{if(settingsRef.current&&!settingsRef.current.contains(e.target))setShowSettings(false)};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[])
  useEffect(()=>{const h=e=>{if(e.shiftKey&&e.key==='Tab'){e.preventDefault();setView(v=>v==='map'?'flow':'map')}if((e.ctrlKey||e.metaKey)&&e.key==='b'){e.preventDefault();setPanelOpen(v=>!v)}if(e.key==='Escape'){setDetailOpen(false);setShowShareModal(false);setShowExportMenu(false);setShowIncForm(false);setMapClickMode(false)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[])

  // Map init
  useEffect(()=>{if(mapRef.current)return;import('leaflet').then(mod=>{const Lf=mod.default||mod;LfRef.current=Lf;delete Lf.Icon.Default.prototype._getIconUrl;Lf.Icon.Default.mergeOptions({iconRetinaUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png'});const map=Lf.map(mapContainerRef.current,{zoomControl:true}).setView([9.5,30.5],6);mapRef.current=map;const bl=makeTile(Lf,baseLayerId,theme);bl.addTo(map);baseLayerRef.current=bl;if(ae){const layers=renderEventToMap(Lf,ae,mapAnims);Object.values(layers).forEach(l=>l.addTo(map));eventLayersRef.current=layers;if(ae.region?.bounds)map.fitBounds(ae.region.bounds,{padding:[30,30]})}})},[])
  useEffect(()=>{const map=mapRef.current,Lf=LfRef.current;if(!map||!Lf)return;const handler=e=>{if(!mapClickMode)return;setIncForm(p=>({...p,a:e.latlng.lat,o:e.latlng.lng}));if(clickMarkerRef.current)map.removeLayer(clickMarkerRef.current);clickMarkerRef.current=Lf.circleMarker([e.latlng.lat,e.latlng.lng],{radius:12,fillColor:'#C9A84C',color:'#FFF',weight:3,fillOpacity:0.7}).addTo(map);setMapClickMode(false)};map.on('click',handler);return()=>map.off('click',handler)},[mapClickMode])
  useEffect(()=>{const map=mapRef.current,Lf=LfRef.current;if(!map||!Lf||!ae)return;Object.values(eventLayersRef.current).forEach(l=>{try{map.removeLayer(l)}catch{}});const layers=renderEventToMap(Lf,ae,mapAnims);Object.entries(layers).forEach(([k,l])=>{if(dataLayers[k]!==false)l.addTo(map)});eventLayersRef.current=layers;if(ae.region?.bounds)map.fitBounds(ae.region.bounds,{padding:[30,30]});setTimeout(()=>map.invalidateSize(),200)},[activeEventId])
  useEffect(()=>{const map=mapRef.current,Lf=LfRef.current;if(!map||!Lf)return;if(baseLayerRef.current)map.removeLayer(baseLayerRef.current);const l=makeTile(Lf,baseLayerId,theme);l.addTo(map);l.bringToBack();baseLayerRef.current=l;ss('bl',baseLayerId)},[baseLayerId,theme])
  useEffect(()=>{const map=mapRef.current,Lf=LfRef.current;if(!map||!Lf)return;if(sentinelRef.current){map.removeLayer(sentinelRef.current);sentinelRef.current=null}if(sentinel2){const s=Lf.tileLayer.wms('https://sh.dataspace.copernicus.eu/ogc/wms/'+COPERNICUS_INSTANCE,{layers:'TRUE-COLOR',tileSize:512,format:'image/png',transparent:true,maxcc:30,minZoom:6,maxZoom:16,time:'2025-10-01/2026-02-12'});s.addTo(map);sentinelRef.current=s}},[sentinel2])
  const toggleDL=useCallback(key=>{setDataLayers(p=>{const n={...p,[key]:!p[key]};const map=mapRef.current,grp=eventLayersRef.current[key];if(map&&grp){if(n[key])grp.addTo(map);else map.removeLayer(grp)}return n})},[])
  useEffect(()=>{if(view==='map'&&mapRef.current)setTimeout(()=>mapRef.current.invalidateSize(),200)},[view,panelOpen,detailOpen])

  const upEv=(id,patch)=>{setEvents(p=>p.map(e=>e.id===id?{...e,...patch,updatedAt:new Date().toISOString().slice(0,10)}:e))}
  const addEvent=()=>{const n=createEvent({name:'New Event '+(events.length+1)});setEvents(p=>[...p,n]);setActiveEventId(n.id);setDetailOpen(true);setDetailTab('overview')}
  const delEvent=id=>{if(events.length<=1)return;setEvents(p=>p.filter(e=>e.id!==id));if(activeEventId===id)setActiveEventId(events.find(e=>e.id!==id)?.id);setDetailOpen(false)}
  const selEvent=id=>{setActiveEventId(id);setDetailOpen(true);setDetailTab('overview')}
  const addBrief=()=>{const txt=briefInput.trim();if(!txt)return;upEv(activeEventId,{briefs:[...(ae.briefs||[]),{id:'b_'+Date.now(),text:txt,ts:new Date().toISOString(),archived:false}],brief:txt});setBriefInput('')}
  const archBrief=bid=>{const bs=(ae.briefs||[]).map(b=>b.id===bid?{...b,archived:true}:b);upEv(activeEventId,{briefs:bs,brief:bs.filter(b=>!b.archived).pop()?.text||''})}
  const merged=()=>(ae.briefs||[]).map(b=>`[${new Date(b.ts).toLocaleDateString()}] ${b.text}`).join('\n\n')

  const analyzeBrief=async()=>{const txt=briefInput.trim()||ae.brief;if(!txt||!apiKey)return;setBriefAnalyzing(true);try{const res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:aiModel,max_tokens:2048,messages:[{role:'user',content:BRIEF_ANALYSIS_PROMPT+' '+txt}]})});const data=await res.json();if(data.error)throw new Error(data.error.message);let raw='';if(data.content)data.content.forEach(b=>{if(b.type==='text')raw+=b.text});const m=raw.match(/\[[\s\S]*\]/);if(m){const ps=JSON.parse(m[0]);const ni=ps.map((p,i)=>({id:'ai_'+Date.now()+'_'+i,dt:p.dt||new Date().toISOString().slice(0,10),a:p.a,o:p.o,tp:p.tp||'displacement',s:p.s||'medium',ti:p.ti||'AI',d:p.d||'',ac:p.ac||'Unknown',og:p.og||'AI'}));const mg=[...(ae.incidents||[]),...ni];upEv(activeEventId,{incidents:mg});reRenderMap({...ae,incidents:mg});if(ni[0])mapRef.current?.setView([ni[0].a,ni[0].o],8);setChatMsgs(p=>({...p,[activeEventId]:[...(p[activeEventId]||[]),{role:'a',text:`🗺️ Added ${ni.length} incident(s).`}]}))}}catch(e){setChatMsgs(p=>({...p,[activeEventId]:[...(p[activeEventId]||[]),{role:'a',text:'❌ '+e.message}]}))};setBriefAnalyzing(false)}

  const reRenderMap=(ev)=>{const map=mapRef.current,Lf=LfRef.current;if(!map||!Lf)return;Object.values(eventLayersRef.current).forEach(l=>{try{map.removeLayer(l)}catch{}});const layers=renderEventToMap(Lf,ev,mapAnims);Object.entries(layers).forEach(([k,l])=>{if(dataLayers[k]!==false)l.addTo(map)});eventLayersRef.current=layers}

  const sendMsg=async()=>{const msg=inputVal.trim();if(!msg||busy)return;const eid=activeEventId;if(!apiKey){setChatMsgs(p=>({...p,[eid]:[...(p[eid]||[]),{role:'u',text:msg},{role:'a',text:'⚠️ '+_('notConfigured')}]}));setInputVal('');return};setChatMsgs(p=>({...p,[eid]:[...(p[eid]||[]),{role:'u',text:msg}]}));setInputVal('');setBusy(true);const hist=[...(chatHist[eid]||[]),{role:'user',content:msg}];setChatHist(p=>({...p,[eid]:hist}));try{const res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:aiModel,max_tokens:1024,system:buildSystemPrompt(ae),messages:hist.slice(-12)})});const d=await res.json();if(d.error)throw new Error(d.error.message);let txt='';if(d.content)d.content.forEach(b=>{if(b.type==='text')txt+=b.text});setChatMsgs(p=>({...p,[eid]:[...(p[eid]||[]),{role:'a',text:txt||'—'}]}));setChatHist(p=>({...p,[eid]:[...(p[eid]||[]),{role:'assistant',content:txt}]}))}catch(e){setChatMsgs(p=>({...p,[eid]:[...(p[eid]||[]),{role:'a',text:'❌ '+e.message}]}))};setBusy(false)}
  const testKey=async()=>{if(!apiKey)return;setBusy(true);try{const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:aiModel,max_tokens:20,messages:[{role:'user',content:'Say OK'}]})});const d=await r.json();if(d.error){setAiStatus('error');alert('❌ '+d.error.message)}else{setAiStatus('ready');alert('✅')}}catch(e){alert('❌ '+e.message)};setBusy(false)}
  const addNote=()=>{const txt=noteInput.trim();if(!txt)return;upEv(activeEventId,{notebook:[...(ae.notebook||[]),{id:'n_'+Date.now(),author:'User',type:'note',text:txt,ts:new Date().toISOString()}]});setNoteInput('')}
  const noteText=text=>{const ps=text.split(/(@\w+)/g);return ps.map((p,i)=>{if(p.startsWith('@')){const r=p.slice(1),inc=(ae?.incidents||[]).find(x=>x.id===r||x.ti.toLowerCase().includes(r.toLowerCase()));if(inc)return<span key={i} onClick={()=>flyTo(inc.a,inc.o)} style={{color:'var(--accent)',cursor:'pointer',fontWeight:600,textDecoration:'underline dotted'}}>{p}</span>;return<span key={i} style={{color:'var(--accent)',fontWeight:600}}>{p}</span>}return<span key={i}>{p}</span>})}
  const genShare=()=>{if(!ae)return;setShareUrl(location.origin+location.pathname+'#/share/'+encodeShare(ae));setShowShareModal(true)}
  const cpShare=()=>{navigator.clipboard.writeText(shareUrl).then(()=>{setCopyFeedback(_('copied'));setTimeout(()=>setCopyFeedback(''),2000)})}
  const expGeo=()=>{dlFile(JSON.stringify(eventToGeoJSON(ae),null,2),ae.name.replace(/\s+/g,'_')+'.geojson','application/geo+json');setShowExportMenu(false)}
  const expCSV=()=>{dlFile(eventToCSV(ae),ae.name.replace(/\s+/g,'_')+'.csv','text/csv');setShowExportMenu(false)}
  const expMD=()=>{dlFile(eventToReport(ae),ae.name.replace(/\s+/g,'_')+'.md');setShowExportMenu(false)}
  const subInc=()=>{if(!incForm.ti||incForm.a===null)return;const ni={id:'inc_'+Date.now(),dt:new Date().toISOString().slice(0,10),a:incForm.a,o:incForm.o,tp:incForm.tp,s:incForm.s,ti:incForm.ti,d:incForm.d,ac:incForm.ac||'Unknown',og:incForm.og||'Field'};const mg=[...(ae.incidents||[]),ni];upEv(activeEventId,{incidents:mg});reRenderMap({...ae,incidents:mg});mapRef.current?.setView([ni.a,ni.o],9);if(clickMarkerRef.current){mapRef.current.removeLayer(clickMarkerRef.current);clickMarkerRef.current=null};setShowIncForm(false);setIncForm({ti:'',d:'',tp:'displacement',s:'medium',ac:'',og:'',a:null,o:null})}
  const loadInfra=async type=>{const map=mapRef.current,Lf=LfRef.current;if(!map||!Lf)return;if(infraGroupsRef.current[type]){map.removeLayer(infraGroupsRef.current[type]);delete infraGroupsRef.current[type];setInfraLayers(p=>{const n={...p};delete n[type];return n});return};setInfraLoading(type);try{const q=buildOverpassQuery(type,map.getBounds());const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:'data='+encodeURIComponent(q)});const d=await r.json();const g=Lf.layerGroup();const col={hospitals:'#E8553A',water:'#4BA8CC',roads:'#8B7355'};(d.elements||[]).forEach(el=>{const lat=el.lat||el.center?.lat,lon=el.lon||el.center?.lon;if(type==='roads'&&el.geometry)Lf.polyline(el.geometry.map(p=>[p.lat,p.lon]),{color:col[type],weight:2,opacity:0.6}).addTo(g);else if(lat&&lon)Lf.circleMarker([lat,lon],{radius:5,fillColor:col[type],color:'#FFF',weight:1,fillOpacity:0.8}).bindPopup(el.tags?.name||type).addTo(g)});g.addTo(map);infraGroupsRef.current[type]=g;setInfraLayers(p=>({...p,[type]:true}))}catch(e){console.error(e)};setInfraLoading('')}
  const flyTo=(a,o)=>mapRef.current?.setView([a,o],9)
  const layerOpts=theme==='dark'?[{id:'dark',name:'CartoDB Dark',desc:'Dark'},...BASE_LAYERS.filter(l=>l.id!=='osm')]:BASE_LAYERS
  const dlDefs=[{k:'incidents',l:_('incidents')},{k:'access',l:_('noAccess')},{k:'risks',l:_('risks')},{k:'corridor',l:_('corridor')}]

  return(
  <div className="app-layout">
    {/* LEFT */}
    <div className={`panel${panelOpen?'':' collapsed'}`}>
      <div className="sidebar-toggle" onClick={()=>setPanelOpen(v=>!v)}>◀</div>
      <div style={{padding:'12px 14px 8px',borderBottom:'1px solid var(--border-subtle)'}}><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{width:8,height:8,borderRadius:'50%',background:'var(--danger)',boxShadow:'0 0 6px var(--danger-glow)'}}/><span style={{fontSize:'calc(var(--fs)*.88)',fontWeight:700,letterSpacing:'.04em'}}>{_('corridorPlanner')}</span><span style={{fontSize:'calc(var(--fs)*.48)',color:aiStatus==='ready'?'var(--success)':'var(--text-faint)',background:aiStatus==='ready'?'var(--success)11':'var(--surface-card)',padding:'2px 6px',borderRadius:3,fontWeight:700,marginLeft:'auto'}}>{aiStatus==='ready'?'🟢':'⚪'} AI</span></div></div>
      <div style={{padding:'8px 14px',display:'flex',gap:5,borderBottom:'1px solid var(--border-subtle)'}}><div style={{flex:1,position:'relative'}}><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder={_('searchEvents')} style={{...inp,paddingLeft:28}}/><span style={{position:'absolute',left:9,top:'50%',transform:'translateY(-50%)',fontSize:'calc(var(--fs)*.72)',color:'var(--text-faint)',pointerEvents:'none'}}>🔍</span></div><button onClick={addEvent} style={{width:34,height:34,borderRadius:7,border:'1px solid var(--border-input)',background:'var(--surface-card)',color:'var(--accent)',cursor:'pointer',fontSize:'calc(var(--fs)*1)',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:700}}>+</button></div>
      <div style={{display:'flex',padding:'6px 14px',gap:5,borderBottom:'1px solid var(--border-subtle)',flexWrap:'wrap',alignItems:'center'}}>
        {['map','flow'].map(v=>(<button key={v} onClick={()=>setView(v)} style={{padding:'4px 10px',borderRadius:5,border:'none',cursor:'pointer',fontSize:'calc(var(--fs)*.65)',fontWeight:600,fontFamily:'inherit',background:view===v?'var(--text-primary)':'var(--surface-card)',color:view===v?'var(--bg-secondary)':'var(--text-muted)'}}>{v==='map'?'🗺️ '+_('map'):'🔀 '+_('flow')}</button>))}
        <span style={{width:1,height:16,background:'var(--border-primary)',margin:'0 2px'}}/>
        {dlDefs.map(d=>(<button key={d.k} onClick={()=>toggleDL(d.k)} style={{padding:'3px 7px',borderRadius:4,cursor:'pointer',fontSize:'calc(var(--fs)*.55)',fontFamily:'inherit',fontWeight:600,background:dataLayers[d.k]?'var(--accent-bg)':'transparent',color:dataLayers[d.k]?'var(--accent)':'var(--text-faint)',border:'1px solid '+(dataLayers[d.k]?'var(--accent)':'var(--border-primary)')}}>{dataLayers[d.k]?'●':'○'} {d.l}</button>))}
      </div>
      <div style={{flex:1,overflowY:'auto',padding:'6px 8px'}}>
        {fEvts.length===0&&<div style={{textAlign:'center',padding:16,color:'var(--text-faint)'}}>{_('noEvents')}</div>}
        {fEvts.map(ev=>(<div key={ev.id} onClick={()=>selEvent(ev.id)} style={{padding:'10px 12px',borderRadius:8,cursor:'pointer',marginBottom:4,background:ev.id===activeEventId?'var(--accent-bg)':'transparent',border:'1px solid '+(ev.id===activeEventId?'var(--accent)':'var(--border-subtle)')}} onMouseEnter={e=>{if(ev.id!==activeEventId)e.currentTarget.style.background='var(--bg-hover)'}} onMouseLeave={e=>{if(ev.id!==activeEventId)e.currentTarget.style.background='transparent'}}>
          <div style={{display:'flex',alignItems:'center',gap:6}}><span style={{width:6,height:6,borderRadius:'50%',background:(SEVERITY[ev.severity]||SEVERITY.medium).color}}/><span style={{fontSize:'calc(var(--fs)*.78)',fontWeight:600,flex:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{ev.name}</span><span style={svB(ev.severity)}>{ev.severity?.toUpperCase()}</span></div>
          <div style={{fontSize:'calc(var(--fs)*.58)',color:'var(--text-muted)',marginTop:3,paddingLeft:12,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{ev.brief||'—'}</div>
          <div style={{fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)',marginTop:2,paddingLeft:12}}>{ev.incidents?.length||0} inc • {ev.updatedAt}</div>
        </div>))}
      </div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:3,padding:'6px 10px',borderTop:'1px solid var(--border-subtle)'}}>{stats.map(s=>(<div key={s.label} style={{padding:'5px 2px',borderRadius:4,textAlign:'center',background:'var(--surface-card)'}}><div style={{fontSize:'calc(var(--fs)*1)',fontWeight:700,color:s.color}}>{s.value}</div><div style={{fontSize:'calc(var(--fs)*.45)',color:'var(--text-muted)'}}>{s.label}</div></div>))}</div>
      <div ref={settingsRef} style={{borderTop:'1px solid var(--border-subtle)',position:'relative'}}>
        <button onClick={()=>setShowSettings(v=>!v)} style={{width:'100%',padding:'10px 14px',border:'none',background:showSettings?'var(--accent-bg)':'var(--bg-secondary)',cursor:'pointer',display:'flex',alignItems:'center',gap:8,fontFamily:'inherit',fontSize:'calc(var(--fs)*.72)',color:'var(--text-muted)',fontWeight:600}}>⚙️ {_('settings')}<span style={{marginLeft:'auto',fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)'}}>v2.0</span></button>
        {showSettings&&(<div style={{position:'absolute',bottom:'100%',left:0,right:0,maxHeight:'60vh',overflowY:'auto',background:'var(--bg-secondary)',border:'1px solid var(--border-primary)',borderBottom:'none',borderRadius:'12px 12px 0 0',boxShadow:'var(--shadow-lg)',animation:'fadeIn .2s ease'}}>
          <div style={{display:'flex',gap:2,padding:'8px 12px 0',borderBottom:'1px solid var(--border-subtle)'}}>{[{id:'appearance',l:'🎨'},{id:'map',l:'🗺️'},{id:'ai',l:'🤖'},{id:'about',l:'ℹ️'}].map(tb=>(<button key={tb.id} onClick={()=>setSettingsTab(tb.id)} style={{padding:'5px 10px',border:'none',background:'transparent',cursor:'pointer',fontSize:'calc(var(--fs)*.82)',fontFamily:'inherit',color:settingsTab===tb.id?'var(--accent)':'var(--text-faint)',borderBottom:settingsTab===tb.id?'2px solid var(--accent)':'2px solid transparent'}}>{tb.l}</button>))}</div>
          <div style={{padding:'12px 14px'}}>
            {settingsTab==='appearance'&&(<><div style={{marginBottom:12}}><div style={{fontSize:'calc(var(--fs)*.68)',fontWeight:700,marginBottom:5}}>{_('theme')}</div><div style={{display:'flex',background:'var(--surface-card)',borderRadius:7,border:'1px solid var(--border-primary)',overflow:'hidden'}}>{['light','dark'].map(tm=>(<button key={tm} onClick={()=>{setTheme(tm);if(tm==='dark'&&baseLayerId==='osm')setBaseLayerId('dark');if(tm==='light'&&baseLayerId==='dark')setBaseLayerId('osm')}} style={{flex:1,padding:'8px 0',border:'none',cursor:'pointer',fontFamily:'inherit',fontWeight:600,fontSize:'calc(var(--fs)*.68)',background:theme===tm?'var(--accent)':'transparent',color:theme===tm?'#FFF':'var(--text-muted)'}}>{tm==='light'?'☀️':'🌙'} {_(tm)}</button>))}</div></div><div style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:'calc(var(--fs)*.65)',fontWeight:600}}>{_('fontSize')}</span><span style={{fontSize:'calc(var(--fs)*.65)',color:'var(--text-muted)'}}>{fs}px</span></div><input type="range" min="10" max="20" value={fs} onChange={e=>setFs(+e.target.value)} style={{width:'100%',accentColor:'var(--accent)'}}/></div><label style={{display:'flex',alignItems:'center',gap:8,fontSize:'calc(var(--fs)*.68)',cursor:'pointer',marginBottom:12}}><input type="checkbox" checked={mapAnims} onChange={e=>setMapAnims(e.target.checked)} style={{accentColor:'var(--accent)'}}/><b>{_('mapAnims')}</b></label><div><div style={{fontSize:'calc(var(--fs)*.68)',fontWeight:700,marginBottom:5}}>{_('language')}</div><div style={{display:'flex',gap:3,flexWrap:'wrap'}}>{LANGS.map(l=>(<button key={l.id} onClick={()=>setLang(l.id)} style={{padding:'5px 10px',borderRadius:5,border:'1px solid '+(lang===l.id?'var(--accent)':'var(--border-primary)'),background:lang===l.id?'var(--accent-bg)':'transparent',color:lang===l.id?'var(--accent)':'var(--text-muted)',cursor:'pointer',fontFamily:'inherit',fontSize:'calc(var(--fs)*.65)',fontWeight:600}}>{l.name}</button>))}</div></div></>)}
            {settingsTab==='map'&&(<><div style={{marginBottom:10}}><div style={{fontSize:'calc(var(--fs)*.68)',fontWeight:700,marginBottom:5}}>{_('baseLayer')}</div>{layerOpts.map(b=>(<label key={b.id} style={{display:'flex',alignItems:'center',gap:6,padding:'4px 6px',borderRadius:4,cursor:'pointer',fontSize:'calc(var(--fs)*.68)'}}><input type="radio" name="bl" checked={baseLayerId===b.id} onChange={()=>setBaseLayerId(b.id)} style={{accentColor:'var(--accent)'}}/><b>{b.name}</b></label>))}</div><label style={{display:'flex',alignItems:'center',gap:6,padding:'4px 6px',fontSize:'calc(var(--fs)*.68)',cursor:'pointer',borderTop:'1px solid var(--border-subtle)',paddingTop:8}}><input type="checkbox" checked={sentinel2} onChange={e=>setSentinel2(e.target.checked)} style={{accentColor:'var(--accent)'}}/><b>Sentinel-2</b></label><div style={{borderTop:'1px solid var(--border-subtle)',paddingTop:8,marginTop:8}}><div style={{fontSize:'calc(var(--fs)*.68)',fontWeight:700,marginBottom:5}}>{_('infra')} (Overpass)</div><div style={{display:'flex',gap:3,flexWrap:'wrap'}}>{[{k:'hospitals',l:_('hospitals'),e:'🏥'},{k:'water',l:_('waterPoints'),e:'💧'},{k:'roads',l:_('roads'),e:'🛣️'}].map(i=>(<button key={i.k} onClick={()=>loadInfra(i.k)} style={{padding:'4px 8px',borderRadius:4,cursor:'pointer',fontSize:'calc(var(--fs)*.58)',fontFamily:'inherit',fontWeight:600,background:infraLayers[i.k]?'var(--accent-bg)':'var(--surface-card)',color:infraLayers[i.k]?'var(--accent)':'var(--text-muted)',border:'1px solid '+(infraLayers[i.k]?'var(--accent)':'var(--border-primary)')}}>{infraLoading===i.k?'…':i.e} {i.l}</button>))}</div></div></>)}
            {settingsTab==='ai'&&(<><div style={{marginBottom:10}}><div style={{fontSize:'calc(var(--fs)*.68)',fontWeight:700,marginBottom:5}}>{_('apiKey')}</div><div style={{display:'flex',gap:4}}><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="sk-ant-..." style={{...inp,fontFamily:'monospace'}}/><button onClick={testKey} disabled={!apiKey||busy} style={{padding:'7px 10px',borderRadius:6,border:'1px solid var(--border-input)',background:'var(--surface-card)',color:'var(--text-secondary)',cursor:apiKey&&!busy?'pointer':'not-allowed',fontFamily:'inherit',fontSize:'calc(var(--fs)*.62)',fontWeight:600}}>Test</button></div></div><div style={{marginBottom:10}}><div style={{fontSize:'calc(var(--fs)*.68)',fontWeight:700,marginBottom:5}}>{_('model')}</div><div style={{display:'flex',background:'var(--surface-card)',borderRadius:6,border:'1px solid var(--border-primary)',overflow:'hidden'}}>{[{id:'claude-sonnet-4-20250514',l:'Sonnet 4'},{id:'claude-haiku-4-5-20251001',l:'Haiku 4.5'}].map(m=>(<button key={m.id} onClick={()=>setAiModel(m.id)} style={{flex:1,padding:'6px 0',border:'none',cursor:'pointer',fontFamily:'inherit',fontWeight:600,fontSize:'calc(var(--fs)*.62)',background:aiModel===m.id?'var(--accent)':'transparent',color:aiModel===m.id?'#FFF':'var(--text-muted)'}}>{m.l}</button>))}</div></div><div style={{display:'flex',alignItems:'center',gap:5}}><span style={{width:6,height:6,borderRadius:'50%',background:aiStatus==='ready'?'#3B7A57':'#8B7355'}}/><span style={{fontSize:'calc(var(--fs)*.62)',color:'var(--text-muted)'}}>{_(aiStatus==='ready'?'connected':'notConfigured')}</span></div></>)}
            {settingsTab==='about'&&(<div style={{fontSize:'calc(var(--fs)*.68)',color:'var(--text-secondary)',lineHeight:1.8}}><b style={{fontSize:'calc(var(--fs)*.82)'}}>Corridor Planner</b><div style={{color:'var(--text-muted)'}}>v2.0 Final — EN/TR/FR/AR</div><div style={{marginTop:4,fontSize:'calc(var(--fs)*.55)',color:'var(--text-faint)'}}>Ctrl+B • Shift+Tab • Esc</div></div>)}
          </div>
        </div>)}
      </div>
    </div>
    {!panelOpen&&<div onClick={()=>setPanelOpen(true)} style={{position:'absolute',top:'50%',left:0,transform:'translateY(-50%)',zIndex:201,width:24,height:48,background:'var(--bg-secondary)',border:'1px solid var(--border-primary)',borderLeft:'none',borderRadius:'0 8px 8px 0',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',color:'var(--text-muted)',fontSize:14}}>▶</div>}

    {/* CANVAS */}
    <div className="canvas">
      <div ref={mapContainerRef} style={{width:'100%',height:'100%',display:view==='map'?'block':'none',cursor:mapClickMode?'crosshair':'grab'}}/>
      {view==='flow'&&<div style={{width:'100%',height:'100%',background:'var(--bg-primary)'}}><svg style={{width:'100%',height:'100%'}}><g>{FLOW_CONNECTIONS.map(([f,tt])=>{const fn=FLOW_NODES.find(n=>n.id===f),tn=FLOW_NODES.find(n=>n.id===tt);return fn&&tn?<path key={f+tt} d={`M${fn.x} ${fn.y}C${fn.x+(tn.x-fn.x)*.4} ${fn.y},${fn.x+(tn.x-fn.x)*.6} ${tn.y},${tn.x} ${tn.y}`} fill="none" stroke={fn.color} strokeWidth="2" opacity=".3"/>:null})}{FLOW_NODES.map(n=><g key={n.id}><circle cx={n.x} cy={n.y} r="50" fill={n.color} opacity=".06"/><circle cx={n.x} cy={n.y} r="38" fill="var(--bg-secondary)" stroke={n.color} strokeWidth="2"/><text x={n.x} y={n.y} textAnchor="middle" dominantBaseline="middle" fill="var(--text-primary)" fontSize="12" fontWeight="600">{n.label}</text></g>)}</g></svg></div>}
      {view==='map'&&<>
        <div style={{position:'absolute',top:14,left:44,zIndex:1000,display:'flex',gap:8,alignItems:'center',pointerEvents:'none'}}><span style={{fontSize:'calc(var(--fs)*.78)',fontWeight:700,background:'var(--glass)',padding:'5px 14px',borderRadius:6}}>{ae?.name||'—'}</span>{ae?.severity==='critical'&&<span style={{fontSize:'calc(var(--fs)*.62)',color:'var(--danger)',background:'var(--danger-bg)',padding:'3px 10px',borderRadius:8,fontWeight:700}}>CRITICAL</span>}</div>
        {mapClickMode&&<div style={{position:'absolute',top:14,right:14,zIndex:1000,background:'var(--accent)',color:'#FFF',padding:'6px 14px',borderRadius:8,fontWeight:700,fontSize:'calc(var(--fs)*.72)',animation:'pulse 1.5s infinite'}}>{_('clickMap')}</div>}
        {!mapClickMode&&<div style={{position:'absolute',top:14,right:14,zIndex:999,display:'flex',gap:5,flexDirection:'column'}}>
          <button onClick={()=>{setShowIncForm(true);setDetailOpen(true);setDetailTab('incidents')}} title={_('reportIncident')} style={{width:36,height:36,borderRadius:8,border:'1px solid var(--border-primary)',background:'var(--glass-strong)',cursor:'pointer',fontSize:'calc(var(--fs)*1)'}}>⚠️</button>
          <button onClick={()=>window.print()} title={_('print')} style={{width:36,height:36,borderRadius:8,border:'1px solid var(--border-primary)',background:'var(--glass-strong)',cursor:'pointer',fontSize:'calc(var(--fs)*1)'}}>🖨️</button>
        </div>}
        {sInc.length>0&&<div style={{position:'absolute',bottom:16,left:'50%',transform:'translateX(-50%)',zIndex:1000,display:'flex',gap:8,background:'var(--glass-strong)',border:'1px solid var(--border-primary)',borderRadius:12,padding:'10px 18px',alignItems:'center'}}><span style={{fontSize:'calc(var(--fs)*.72)',color:'var(--text-muted)',fontWeight:700,marginRight:6}}>{_('timeline')}</span>{sInc.map(inc=><div key={inc.id} title={inc.ti} onClick={()=>flyTo(inc.a,inc.o)} style={{display:'flex',flexDirection:'column',alignItems:'center',cursor:'pointer',padding:'4px 8px',borderRadius:8}} onMouseEnter={e=>e.currentTarget.style.background='var(--bg-hover)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}><span style={{fontSize:'calc(var(--fs)*1.3)'}}>{ICON_MAP[inc.tp]||'⚠️'}</span><span style={{fontSize:'calc(var(--fs)*.62)',color:(SEVERITY[inc.s]||SEVERITY.medium).color,marginTop:3,fontWeight:700}}>{inc.dt.slice(5)}</span></div>)}</div>}
      </>}
    </div>

    {/* RIGHT PANEL */}
    {detailOpen&&ae&&<div style={{width:420,minWidth:420,display:'flex',flexDirection:'column',background:'var(--bg-secondary)',borderLeft:'1px solid var(--border-primary)',zIndex:100,overflow:'hidden'}}>
      <div style={{padding:'12px 14px',borderBottom:'1px solid var(--border-subtle)',display:'flex',alignItems:'flex-start',gap:8}}>
        <div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:5,marginBottom:3}}><span style={svB(ae.severity)}>{ae.severity?.toUpperCase()}</span><span style={{fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)'}}>{ae.status}</span></div><div style={{fontSize:'calc(var(--fs)*.88)',fontWeight:700,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{ae.name}</div></div>
        <div style={{display:'flex',gap:4,flexShrink:0}}>
          <button onClick={genShare} title={_('share')} style={{background:'none',border:'1px solid var(--border-primary)',cursor:'pointer',color:'var(--text-muted)',padding:'4px 8px',borderRadius:5,fontSize:'calc(var(--fs)*.72)'}}>🔗</button>
          <div style={{position:'relative'}}><button onClick={()=>setShowExportMenu(v=>!v)} style={{background:'none',border:'1px solid var(--border-primary)',cursor:'pointer',color:'var(--text-muted)',padding:'4px 8px',borderRadius:5,fontSize:'calc(var(--fs)*.72)'}}>📥</button>{showExportMenu&&<div style={{position:'absolute',top:'100%',right:0,marginTop:4,background:'var(--bg-secondary)',border:'1px solid var(--border-primary)',borderRadius:8,boxShadow:'var(--shadow-md)',zIndex:10,minWidth:150,overflow:'hidden'}}>{[{fn:expGeo,l:'🗺️ GeoJSON'},{fn:expCSV,l:'📊 CSV'},{fn:expMD,l:'📝 Report'}].map(x=><button key={x.l} onClick={x.fn} style={{display:'block',width:'100%',padding:'8px 14px',border:'none',background:'transparent',cursor:'pointer',fontSize:'calc(var(--fs)*.68)',color:'var(--text-secondary)',fontFamily:'inherit',textAlign:'left'}} onMouseEnter={e=>e.currentTarget.style.background='var(--bg-hover)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{x.l}</button>)}</div>}</div>
          <button onClick={()=>setDetailOpen(false)} style={{background:'none',border:'none',cursor:'pointer',color:'var(--text-muted)',fontSize:'calc(var(--fs)*1.1)',padding:'2px 4px'}}>✕</button>
        </div>
      </div>
      <div style={{display:'flex',borderBottom:'1px solid var(--border-subtle)',padding:'0 4px'}}>{[{id:'overview',i:'📋'},{id:'incidents',i:'⚠️'},{id:'ai',i:'🤖'},{id:'notebook',i:'📓'}].map(tb=><button key={tb.id} onClick={()=>setDetailTab(tb.id)} style={{flex:1,padding:'8px 2px',border:'none',background:'transparent',cursor:'pointer',fontSize:'calc(var(--fs)*.72)',fontFamily:'inherit',color:detailTab===tb.id?'var(--accent)':'var(--text-faint)',borderBottom:detailTab===tb.id?'2px solid var(--accent)':'2px solid transparent'}}>{tb.i}</button>)}</div>
      <div style={{flex:1,overflowY:'auto',padding:'12px 14px',display:'flex',flexDirection:'column'}}>
        {/* OVERVIEW */}
        {detailTab==='overview'&&<>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:4,marginBottom:12}}>{stats.map(s=><div key={s.label} style={{padding:'6px 2px',borderRadius:5,textAlign:'center',background:'var(--surface-card)',border:'1px solid var(--border-primary)'}}><div style={{fontSize:'calc(var(--fs)*1)',fontWeight:700,color:s.color}}>{s.value}</div><div style={{fontSize:'calc(var(--fs)*.45)',color:'var(--text-muted)'}}>{s.label}</div></div>)}</div>
          <div style={{marginBottom:12}}><div style={{fontSize:'calc(var(--fs)*.62)',fontWeight:700,color:'var(--text-muted)',marginBottom:4,textTransform:'uppercase'}}>{_('addBrief')}</div><textarea value={briefInput} onChange={e=>setBriefInput(e.target.value)} placeholder="..." style={{...inp,minHeight:60,resize:'vertical',lineHeight:1.6}}/><div style={{display:'flex',gap:5,marginTop:5}}><button onClick={addBrief} style={{flex:1,padding:'7px 0',borderRadius:6,border:'none',background:'var(--accent)',color:'#FFF',cursor:'pointer',fontFamily:'inherit',fontSize:'calc(var(--fs)*.68)',fontWeight:600}}>{_('addBrief')}</button><button onClick={analyzeBrief} disabled={briefAnalyzing||!apiKey} style={{flex:1,padding:'7px 0',borderRadius:6,border:'1px solid var(--accent)',background:'transparent',color:'var(--accent)',cursor:apiKey&&!briefAnalyzing?'pointer':'not-allowed',fontFamily:'inherit',fontSize:'calc(var(--fs)*.68)',fontWeight:600,opacity:apiKey?1:.5}}>{briefAnalyzing?_('analyzing'):_('analyzeMap')}</button></div></div>
          <div style={{marginBottom:12}}><div style={{fontSize:'calc(var(--fs)*.62)',fontWeight:700,color:'var(--text-muted)',marginBottom:4,textTransform:'uppercase'}}>{_('briefs')} ({aBriefs.length})</div>{aBriefs.length===0&&<div style={{fontSize:'calc(var(--fs)*.68)',color:'var(--text-faint)',padding:'8px 0'}}>{_('noBriefs')}</div>}{aBriefs.map(b=><div key={b.id} style={{padding:'8px 10px',borderRadius:6,marginBottom:4,background:'var(--surface-card)',border:'1px solid var(--border-primary)',fontSize:'calc(var(--fs)*.72)',lineHeight:1.6}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:3}}><span style={{fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)'}}>{new Date(b.ts).toLocaleDateString()}</span><button onClick={()=>archBrief(b.id)} style={{fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)',background:'none',border:'none',cursor:'pointer',textDecoration:'underline'}}>{_('archive')}</button></div><div style={{color:'var(--text-secondary)'}}>{b.text}</div></div>)}</div>
          {xBriefs.length>0&&<div style={{marginBottom:12}}><button onClick={()=>setShowArchived(v=>!v)} style={{fontSize:'calc(var(--fs)*.58)',color:'var(--text-faint)',background:'none',border:'none',cursor:'pointer'}}>{showArchived?'▾':'▸'} {_('archived')} ({xBriefs.length})</button>{showArchived&&xBriefs.map(b=><div key={b.id} style={{padding:'6px 10px',borderRadius:5,marginBottom:3,background:'var(--bg-hover)',borderLeft:'3px solid var(--text-faint)',fontSize:'calc(var(--fs)*.65)',opacity:.7}}><div style={{fontSize:'calc(var(--fs)*.48)',color:'var(--text-faint)',marginBottom:2}}>{new Date(b.ts).toLocaleDateString()}</div><div style={{color:'var(--text-muted)'}}>{b.text}</div></div>)}</div>}
          {(ae.briefs||[]).length>1&&<div style={{marginBottom:12}}><div style={{fontSize:'calc(var(--fs)*.62)',fontWeight:700,color:'var(--text-muted)',marginBottom:4,textTransform:'uppercase'}}>📊 {_('progress')}</div><div style={{padding:'10px 12px',borderRadius:7,background:'var(--surface-card)',border:'1px solid var(--border-primary)',fontSize:'calc(var(--fs)*.68)',lineHeight:1.8,maxHeight:180,overflowY:'auto',whiteSpace:'pre-wrap',color:'var(--text-secondary)'}}>{merged()}</div></div>}
          {events.length>1&&<button onClick={()=>{if(confirm('Delete?'))delEvent(ae.id)}} style={{marginTop:'auto',padding:'7px 0',borderRadius:7,border:'1px solid var(--danger)',background:'transparent',color:'var(--danger)',cursor:'pointer',fontFamily:'inherit',fontSize:'calc(var(--fs)*.65)',fontWeight:600,width:'100%'}}>🗑️ {_('deleteEvent')}</button>}
        </>}
        {/* INCIDENTS + FORM */}
        {detailTab==='incidents'&&<>
          {showIncForm&&<div style={{padding:12,borderRadius:8,border:'1px solid var(--accent)',background:'var(--accent-bg)',marginBottom:10,animation:'fadeIn .2s ease'}}>
            <div style={{fontSize:'calc(var(--fs)*.72)',fontWeight:700,marginBottom:8}}>{_('reportIncident')}</div>
            <input value={incForm.ti} onChange={e=>setIncForm(p=>({...p,ti:e.target.value}))} placeholder={_('incTitle')} style={{...inp,marginBottom:5}}/>
            <input value={incForm.d} onChange={e=>setIncForm(p=>({...p,d:e.target.value}))} placeholder={_('incDesc')} style={{...inp,marginBottom:5}}/>
            <div style={{display:'flex',gap:5,marginBottom:5}}>
              <select value={incForm.tp} onChange={e=>setIncForm(p=>({...p,tp:e.target.value}))} style={{...inp,flex:1}}>{INC_TYPES.map(tp=><option key={tp} value={tp}>{ICON_MAP[tp]||'⚠️'} {tp}</option>)}</select>
              <select value={incForm.s} onChange={e=>setIncForm(p=>({...p,s:e.target.value}))} style={{...inp,flex:1}}>{SEV_LEVELS.map(s=><option key={s} value={s}>{s.toUpperCase()}</option>)}</select>
            </div>
            <div style={{display:'flex',gap:5,marginBottom:5}}>
              <input value={incForm.ac} onChange={e=>setIncForm(p=>({...p,ac:e.target.value}))} placeholder={_('incActor')} style={{...inp,flex:1}}/>
              <input value={incForm.og} onChange={e=>setIncForm(p=>({...p,og:e.target.value}))} placeholder={_('incOrg')} style={{...inp,flex:1}}/>
            </div>
            <button onClick={()=>setMapClickMode(true)} style={{width:'100%',padding:'7px 0',borderRadius:6,border:'1px dashed var(--accent)',background:'transparent',color:'var(--accent)',cursor:'pointer',fontFamily:'inherit',fontSize:'calc(var(--fs)*.68)',fontWeight:600,marginBottom:5}}>{incForm.a!==null?`📍 ${incForm.a.toFixed(4)}, ${incForm.o.toFixed(4)}`:_('clickMap')}</button>
            <div style={{display:'flex',gap:5}}><button onClick={subInc} disabled={!incForm.ti||incForm.a===null} style={{flex:1,padding:'7px 0',borderRadius:6,border:'none',background:'var(--accent)',color:'#FFF',cursor:incForm.ti&&incForm.a!==null?'pointer':'not-allowed',fontFamily:'inherit',fontSize:'calc(var(--fs)*.68)',fontWeight:600,opacity:incForm.ti&&incForm.a!==null?1:.5}}>{_('addIncident')}</button><button onClick={()=>setShowIncForm(false)} style={{flex:1,padding:'7px 0',borderRadius:6,border:'1px solid var(--border-primary)',background:'transparent',color:'var(--text-muted)',cursor:'pointer',fontFamily:'inherit',fontSize:'calc(var(--fs)*.68)'}}>{_('cancel')}</button></div>
          </div>}
          {!showIncForm&&<button onClick={()=>setShowIncForm(true)} style={{padding:'8px 0',borderRadius:7,border:'1px dashed var(--accent)',background:'transparent',color:'var(--accent)',cursor:'pointer',fontFamily:'inherit',fontSize:'calc(var(--fs)*.68)',fontWeight:600,marginBottom:8,width:'100%'}}>+ {_('reportIncident')}</button>}
          {sInc.length===0&&<div style={{textAlign:'center',padding:16,color:'var(--text-faint)'}}>{_('noIncidents')}</div>}
          {sInc.map(inc=>{const sv=SEVERITY[inc.s]||SEVERITY.medium;return<div key={inc.id} onClick={()=>flyTo(inc.a,inc.o)} style={{padding:'8px 10px',borderRadius:7,marginBottom:4,cursor:'pointer',border:'1px solid var(--border-primary)',background:'var(--surface-card)'}} onMouseEnter={e=>e.currentTarget.style.borderColor=sv.color} onMouseLeave={e=>e.currentTarget.style.borderColor='var(--border-primary)'}><div style={{display:'flex',alignItems:'center',gap:6}}><span style={{fontSize:'calc(var(--fs)*.95)'}}>{ICON_MAP[inc.tp]||'⚠️'}</span><span style={{flex:1,fontSize:'calc(var(--fs)*.72)',fontWeight:600}}>{inc.ti}</span><span style={svB(inc.s)}>{inc.s.toUpperCase()}</span></div><div style={{fontSize:'calc(var(--fs)*.62)',color:'var(--text-muted)',marginTop:3,paddingLeft:24}}>{inc.d}</div><div style={{fontSize:'calc(var(--fs)*.52)',color:'var(--text-faint)',marginTop:2,paddingLeft:24}}>{inc.dt} • {inc.ac}</div></div>})}
        </>}
        {/* AI */}
        {detailTab==='ai'&&<><div style={{flex:1,overflowY:'auto',display:'flex',flexDirection:'column',gap:6,marginBottom:8}}>{cMsgs.map((m,i)=><div key={i} style={{animation:'fadeIn .3s ease',maxWidth:'94%',alignSelf:m.role==='u'?'flex-end':'flex-start'}}>{m.role==='a'&&<div style={{fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)',marginBottom:2,paddingLeft:4}}>🤖</div>}<div style={{padding:'8px 10px',borderRadius:9,fontSize:'calc(var(--fs)*.75)',lineHeight:1.7,whiteSpace:'pre-wrap',wordBreak:'break-word',...(m.role==='u'?{background:'var(--surface-msg-user)',color:'var(--surface-msg-user-text)',borderBottomRightRadius:3}:{background:'var(--surface-msg-ai)',border:'1px solid var(--surface-msg-ai-border)',color:'var(--surface-msg-ai-text)',borderBottomLeftRadius:3})}}>{m.text}</div></div>)}{busy&&<div style={{alignSelf:'flex-start'}}><div style={{padding:'8px 10px',borderRadius:9,background:'var(--surface-msg-ai)',border:'1px solid var(--surface-msg-ai-border)'}}><span style={{animation:'blink 1.2s infinite',color:'var(--text-muted)'}}>{_('thinking')}</span></div></div>}<div ref={chatEndRef}/></div><div style={{display:'flex',gap:5}}><input value={inputVal} onChange={e=>setInputVal(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendMsg()} placeholder={apiKey?'…':_('notConfigured')} disabled={busy} style={{...inp,flex:1}}/><button onClick={sendMsg} disabled={busy} style={{padding:'8px 12px',borderRadius:7,border:'none',background:busy?'var(--text-faint)':'var(--text-primary)',color:'var(--bg-secondary)',cursor:busy?'not-allowed':'pointer',fontWeight:700}}>↵</button></div></>}
        {/* NOTEBOOK */}
        {detailTab==='notebook'&&<><div style={{flex:1,overflowY:'auto'}}>{(!ae.notebook||!ae.notebook.length)&&<div style={{textAlign:'center',padding:16,color:'var(--text-faint)'}}>{_('noNotes')}</div>}{(ae.notebook||[]).map(n=><div key={n.id} style={{padding:'8px 10px',borderRadius:7,marginBottom:4,background:'var(--surface-card)',border:'1px solid var(--border-primary)'}}><div style={{display:'flex',alignItems:'center',gap:6,marginBottom:3}}><span style={{fontSize:'calc(var(--fs)*.62)',fontWeight:700,color:'var(--accent)'}}>{n.author}</span><span style={{fontSize:'calc(var(--fs)*.48)',padding:'1px 4px',borderRadius:3,background:'var(--accent-bg)',color:'var(--accent)'}}>{n.type}</span><span style={{fontSize:'calc(var(--fs)*.48)',color:'var(--text-faint)',marginLeft:'auto'}}>{new Date(n.ts).toLocaleDateString()}</span></div><div style={{fontSize:'calc(var(--fs)*.72)',lineHeight:1.7,color:'var(--text-secondary)'}}>{noteText(n.text)}</div></div>)}</div><div style={{fontSize:'calc(var(--fs)*.5)',color:'var(--text-faint)',marginBottom:4}}>{_('mentionHint')}</div><div style={{display:'flex',gap:5}}><input value={noteInput} onChange={e=>setNoteInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addNote()} placeholder={_('addNote')} style={{...inp,flex:1}}/><button onClick={addNote} style={{padding:'8px 12px',borderRadius:7,border:'none',background:'var(--accent)',color:'#FFF',cursor:'pointer',fontWeight:700}}>{_('addBrief').split(' ')[0]}</button></div></>}
      </div>
    </div>}

    {/* SHARE MODAL */}
    {showShareModal&&<div style={{position:'fixed',inset:0,zIndex:9999,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,.5)'}} onClick={()=>setShowShareModal(false)}><div onClick={e=>e.stopPropagation()} style={{width:480,maxWidth:'90vw',background:'var(--bg-secondary)',border:'1px solid var(--border-primary)',borderRadius:14,padding:'20px 24px',boxShadow:'var(--shadow-lg)',animation:'fadeIn .2s ease'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><span style={{fontSize:'calc(var(--fs)*.92)',fontWeight:700}}>🔗 {_('shareEvent')}</span><button onClick={()=>setShowShareModal(false)} style={{background:'none',border:'none',cursor:'pointer',color:'var(--text-muted)',fontSize:'calc(var(--fs)*1.1)'}}>✕</button></div><div style={{fontSize:'calc(var(--fs)*.72)',color:'var(--text-muted)',marginBottom:10}}>{_('shareDesc')}</div><div style={{display:'flex',gap:6}}><input readOnly value={shareUrl} style={{...inp,flex:1,fontFamily:'monospace',fontSize:'calc(var(--fs)*.6)'}} onFocus={e=>e.target.select()}/><button onClick={cpShare} style={{padding:'8px 16px',borderRadius:7,border:'none',background:'var(--accent)',color:'#FFF',cursor:'pointer',fontWeight:700,whiteSpace:'nowrap'}}>{copyFeedback||_('copy')}</button></div></div></div>}
  </div>)
}
